server:
  port: 8050
spring:
  application:
    name: AnCF
#  数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/ancf?tinyInt1isBit=false&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: GuliHikariPool
#序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #mail邮箱配置
  mail:
    host: smtp.qq.com
    port: 465
    username: anyuzhao@qq.com
    password: zngjtedtoxzhdfca
    protocol: smtps
#    Redis配置
  redis:
    host: 172.17.0.1
    port: 6379
    database: 1

  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#mybatis-plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: status
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    #枚举包
  type-enums-package: com.anyu.common.model.enums


graphiql:
  cdn:
    enabled: true

#jwt配置
app:
  jwt:
    aud: add
    iss: anyu
#日志配置
logging:
  level:
    com.anyu: debug
#graphql配置
graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET, HEAD, POST
      max-age: 12000
      allow-credentials: true
      allowed-headers: "*"

#    subscriptions:
#      websocket:
#        path: /subscriptions

#aliyun OSS 配置
aliyun:
  oss:
    bucket-name: ancf
    endpoint: oss-cn-chengdu.aliyuncs.com
    key-id: LTAI5t849BE4hv1eR2pN49HZ
    key-secret: sGyO6n6D2jMjJnWVJOCBmFELk7rTTq
